---

- name: "copy: Copy script to {{ bsd_yazvs_bin_dir }}.patched"
  ansible.builtin.copy:
    src: "{{ bsd_yazvs_source_dir }}/{{ bsd_yazvs_bin }}"
    dest: "{{ bsd_yazvs_source_dir }}/{{ bsd_yazvs_bin }}.patched"
    owner: root
    group: wheel
    mode: "0755"
    remote_src: true
  changed_when: false
  tags: bsd_yazvs_source_copy

- name: "copy: Which perl"
  ansible.builtin.command:
    cmd: which perl
  register: which_perl
  changed_when: false
  tags: bsd_yazvs_which_perl

- name: "copy: Patch {{ which_perl.stdout }} in
                     {{ bsd_yazvs_source_dir }}/{{ bsd_yazvs_bin }}.patched"
  ansible.builtin.lineinfile:
    dest: "{{ bsd_yazvs_source_dir }}/{{ bsd_yazvs_bin }}.patched"
    regexp: "#!"
    line: "#!{{ which_perl.stdout }}"
  changed_when: false
  when: not ansible_check_mode
  tags: bsd_yazvs_source_patch

- name: "copy: Create directory for installation {{ bsd_yazvs_bin_dir }}"
  ansible.builtin.file:
    state: directory
    path: "{{ bsd_yazvs_bin_dir }}"
    mode: "{{ bsd_yazvs_bin_dir_mode|default(omit) }}"
  tags: bsd_yazvs_bindir_create

- name: "copy: Copy {{ bsd_yazvs_source_dir }}/{{ bsd_yazvs_bin }}.patched to
                    {{ bsd_yazvs_bin_dir }}/{{ bsd_yazvs_bin }}"
  ansible.builtin.copy:
    src: "{{ bsd_yazvs_source_dir }}/{{ bsd_yazvs_bin }}.patched"
    dest: "{{ bsd_yazvs_bin_dir }}/{{ bsd_yazvs_bin }}"
    owner: root
    group: wheel
    mode: "0755"
    remote_src: true
  tags: bsd_yazvs_bin_copy

# EOF
...
