---
- name: "Copy: Copy script to {{ bsd_yazvs_bin_dir ~ '.patched' }}"
  tags: bsd_yazvs_source_copy
  ansible.builtin.copy:
    src: "{{ bsd_yazvs_source_dir }}/{{ bsd_yazvs_bin }}"
    dest: "{{ bsd_yazvs_source_dir }}/{{ bsd_yazvs_bin }}.patched"
    owner: root
    group: wheel
    mode: "0755"
    remote_src: true
  changed_when: false

- name: "Copy: Which perl"
  tags: bsd_yazvs_which_perl
  register: which_perl
  changed_when: false
  ansible.builtin.command:
    cmd: which perl

- name: "Copy: Patch perl in {{ bsd_yazvs_source_dir  ~ '/' ~  bsd_yazvs_bin ~ '.patched' }}"
  tags: bsd_yazvs_source_patch
  changed_when: false
  ansible.builtin.lineinfile:
    dest: "{{ bsd_yazvs_source_dir }}/{{ bsd_yazvs_bin }}.patched"
    insertbefore: BOF
    regexp: '#!'
    line: '#!{{ which_perl.stdout }}'

- name: "Copy: Create directory for installation {{ bsd_yazvs_bin_dir }}"
  tags: bsd_yazvs_bindir_create
  ansible.builtin.file:
    state: directory
    path: "{{ bsd_yazvs_bin_dir }}"
    mode: "{{ bsd_yazvs_bin_dir_mode | d(omit) }}"

- name: "Copy: Copy patched script to {{ bsd_yazvs_bin_dir  ~ '/' ~ bsd_yazvs_bin }}"
  tags: bsd_yazvs_bin_copy
  ansible.builtin.copy:
    src: "{{ bsd_yazvs_source_dir }}/{{ bsd_yazvs_bin }}.patched"
    dest: "{{ bsd_yazvs_bin_dir }}/{{ bsd_yazvs_bin }}"
    owner: root
    group: wheel
    mode: "0755"
    remote_src: true


# EOF
