---

- name: "cron: Configure cron MAILTO={{ bsd_yazvs_cron_mailto }}"
  community.general.cronvar:
    name: MAILTO
    value: "{{ bsd_yazvs_cron_mailto }}"
    user: "{{ bsd_yazvs_cron_user }}"

- name: "cron: Configure cron DNSSEC check"
  ansible.builtin.cron:
    name: Check DNSSEC
    user: "{{ bsd_yazvs_cron_user }}"
    job: "{{ bsd_yazvs_cron_command }}"
    hour: "{{ bsd_yazvs_cron_hour }}"
    minute: "{{ bsd_yazvs_cron_minute }}"

# EOF
...
