---

- include: packages.yml
  tags:
    - bsd_yazvs_packages
    - bsd_yazvs_all

- include: source.yml
  tags:
    - bsd_yazvs_source
    - bsd_yazvs_all

- include: copy.yml
  tags:
    - bsd_yazvs_copy
    - bsd_yazvs_all

- include: cron.yml
  tags:
    - bsd_yazvs_cron
    - bsd_yazvs_all

# EOF
...
