---
# tasks for vbotka.yazvs

- include: packages.yml
  tags: bsd_yazvs_packages

- include: source.yml
  tags: bsd_yazvs_source

- include: copy.yml
  tags: bsd_yazvs_copy

- include: script.yml
  tags: bsd_yazvs_script

- include: cron.yml
  tags: bsd_yazvs_cron

# EOF
...
