---
# tasks for yazvs

- name: Test supported distro
  fail:
    msg: "[ERROR] Unsupported distribution."
  when: not ansible_distribution in bsd_yazvs_supported_distributions
  tags: allways

- include: packages.yml
  when: bsd_yazvs_install|bool
  tags: bsd_yazvs_packages

- include: source.yml
  tags: bsd_yazvs_source

- include: copy.yml
  tags: bsd_yazvs_copy

- include: script.yml
  tags: bsd_yazvs_script

- include: cron.yml
  when: bsd_yazvs_cron|bool
  tags: bsd_yazvs_cron

# EOF
...
