---

- name: "script: Create {{ bsd_Validate_DNS_KEYDIR }}"
  file:
    state: directory
    path: "{{ bsd_Validate_DNS_KEYDIR }}"

- name: "script: Create script for cron"
  template:
    src: Validate-DNS.j2
    dest: "{{ bsd_yazvs_bin_dir }}/Validate-DNS.sh"
    owner: "root"
    group: "wheel"
    mode: "0755"
    backup: "{{ bsd_yazvs_backup_conf }}"

# EOF
...
