---
- name: "Script: Create {{ bsd_Validate_dns_keydir }}"
  ansible.builtin.file:
    state: directory
    path: "{{ bsd_validate_dns_keydir }}"
    mode: "{{ bsd_validate_dns_keydir_mode | default(omit) }}"

- name: "Script: Create script for cron"
  ansible.builtin.template:
    src: Validate-DNS.j2
    dest: "{{ bsd_yazvs_bin_dir }}/Validate-DNS.sh"
    owner: root
    group: wheel
    mode: "0755"
    backup: "{{ bsd_yazvs_backup_conf }}"

# EOF
